### ISSUE TITLE
FEATURE REQUEST: link package folder to Windows Explorer from admin info page

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/simple-server#29]
(from #26 closed)

"To add packages to the feed put package files (.nupkg files) in the folder "C:\tools\chocolatey.server\App_Data\Packages"." 

It would be useful if the packages location was a link that could be clicked and have Windows Explorer run and pop up at that location.

**Comment by bcurran3** [comment]
pseudo reference - https://stackoverflow.com/questions/6267546/how-do-i-associate-a-custom-mime-type-to-my-local-application-in-the-major-brows

Looks like it would need end user configuration....I haven't thought through security ramifications if any.

**Comment by bcurran3** [comment]
REVISION: Skip Windows Explorer, display it in the browser.

Simple:
link = file:///C:/tools/chocolatey.server/

**Comment by gep13** [comment]
Based on some hunting around this morning, it looks like this is not going to be possible.  Security restrictions in the browser block any attempt to add this in.

I tested out the strategy of using `file:///` links, and this doesn't work.

If you can provide a mechanism where this work reliably, I would be happy to get this added in, but for now, I am going to go ahead and close this issue.
