### ISSUE TITLE
Change default package URL?

### ISSUE THREAD

**Issue by 0w8States** [chocolatey-community/simple-server#65]
Hi!

Is it possible to change the default package URL from "http://localhost/chocolatey" to something like "http://localhost/stable" ?

I've been trying to find this in the web.conf but can't seem to locate if it's possible or not. 

Thank you!

**Comment by pauby** [comment]
I'm assuming you asked the question over on [Reddit](https://www.reddit.com/r/chocolatey/comments/1en97iz/can_i_change_chocolateyserver_default_url/)? I've answered over there.

> [Chocolatey.Server (aka Simple Server)](https://github.com/chocolatey-community/simple-server) is not supported and the repository will soon be archived. In the meantime, there is a notice on the [README](https://github.com/chocolatey-community/simple-server/blob/master/README.md) which also points to an [issue about it](https://github.com/chocolatey-community/simple-server/issues/63). We advise you not to use it.

> Simple Server is an IIS website and should be able to change what you need to in there.

**Comment by 0w8States** [comment]
I did! Thank you :)
